import type { Metadata } from "next";
import { ThemeProvider } from "@mui/material/styles";
import { theme } from "@/theme";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import { FC } from "react";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Navbar />
            {children}
            <Footer />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
};

export default RootLayout;
